clone_depth: 1

# use Windows 10
image: Visual Studio 2015

# matrix from w3's appveyor yml (https://github.com/w3c/respec/blob/develop/appveyor.yml)
matrix:
  fast_finish: true

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - appveyor-retry npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run test:windows

# Don't actually build.
build: off

# build cache to preserve files/folders between builds
cache:
  - node_modules  # local npm modules
